name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start AI Observer with '...'
        2. Configure Claude Code/Gemini CLI/Codex CLI to send telemetry
        3. Do '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install AI Observer?
      options:
        - Docker
        - Homebrew
        - Binary download
        - Built from source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AI Observer Version
      description: Run `ai-observer --version` or check the dashboard footer
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: dropdown
    id: ai-tool
    attributes:
      label: AI Tool(s) Affected
      description: Which AI coding tool(s) are you using?
      multiple: true
      options:
        - Claude Code
        - Gemini CLI
        - OpenAI Codex CLI
        - N/A (dashboard/API issue)

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: "macOS 14.0, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant log output (from AI Observer or the AI tool)
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem.
