name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Dashboard UI
        - Metrics visualization
        - Logs view
        - Traces view
        - OTLP ingestion
        - API
        - Docker/deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: ai-tool
    attributes:
      label: Related AI Tool
      description: Is this feature specific to a particular AI tool?
      options:
        - All tools
        - Claude Code
        - Gemini CLI
        - OpenAI Codex CLI
        - Not tool-specific

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
